### PR TITLE
Support for all device cameras

### PR DESCRIPTION
**Pull request by pcm2a**
This PR contains a few features that I wasn't sure if it made sense to split up. I also included some examples in the sampleApp CameraFragment. I can remove them if needed.

- Starting any of the devices cameras, not just back/front. Useful when the user comes back and wants to start on the same facing direction.
`start(cameraId: Int)`
- Switching to the next camera, supporting all cameras
`camera.nextCamera()`
- Switching to any camera using the "facing" variable
`camera.facing = 2` would switch to camera 2 
- Retrieving a camera map that contains information about all of the cameras
-- Retrieve camera ids by facing direction (all front or back cameras)
-- Retrieve CameraCharacteristics by camera id
-- Retrieve the direction a camera is facing by camera id

If a device has two back cameras the device's camera will have one toggle to change from front to back. When on the back camera there will be additional icons to switch between each back camera. An example would be an icon of a "regular" view and a "wide angle" view or a "zoom" view. The camera map will provide enough information to display all of this in the UI. Another example is the LG V40 that has three back cameras, with icons for wide angle, regular and zoom.

### CODE REVIEW

**Comment by pcm2a** [comment]
Found a bug where switching camera modes can cause the camera to change because it is calling start() instead of start(cameraId).

**Comment by pcm2a** [comment]
I have fixed the issue. So what was happening is if the user was on camera #2 and start() is called the chooseByFacing method would pick camera 0 or 1 and the camera would suddenly change. To fix this I call start(cameraId) from start and pass in camera.facing. I'm not sure the method `chooseCameraIdByFacing` is needed.

**Comment by pcm2a** [comment]
I have merged in the latest from development

**Comment by pcm2a** [comment]
Updated this PR with the latest from the development branch.

**Comment by pvasa** [comment]
@pcm2a I am recreating `development` branch as it seems to be in bad state. I will reopen your PR against the new branch.

**Pull request closed without merging**
