### PR TITLE
Switch through cameras of set facing

### PR DESCRIPTION
**Pull request by pcm2a**
I have closed the other PR and remade the changes from the latest development branch. I also refactored and made the changes simpler for the user. Almost all new phones come with more than 2 cameras now and in some cases 4 or 5 cameras.

CameraView:
start() -> User can still call this to start the camera, getting the default rear facing

start(cameraId) -> New feature to allow starting right to a camera, for example remembering that the user was on the back camera.

nextCamera() -> New feature that will cycle through all of the devices cameras, in the order that the device presents them. Example: 0 (rear), 1 (front), 2 (rear) for a LG G5 or LG G6.

### CODE REVIEW

**Comment by pvasa** [comment]
@pcm2a I have made some improvements to the camera switching implementation also clearly separated cameraId and facing as they are different. Can you please give it a try on a multi camera device? Let me know if there are any issues.

**Comment by pcm2a** [comment]
Thanks, I will review and test it out this week! Looking forward to it.

**Comment by pcm2a** [comment]
I tested the changes and I was able to cycle through the cameras facing front or back. With this change to getNextCameraId I think we will need to expose some other things:

1. We should store the actual camera id and have a way to return it. For example camera.facing returns the current facing. camera.cameraId could return the cameraId. This will be needed if the user last used camera 4 and when the camera is launched we want to start on that camera.

2. Method to return the number of cameras for the current facing direction. If there is only one camera facing back then there won't be a need to show extra icons for cycling through back cameras.

3. Some easy way to just flip though all of the cameras. If I want to just have one icon for cycling between all of the devices cameras how would I do that? One option would be a convenience method that returns all of the camera ids for the current facing direction.

Sudo code using the above methods to flip through all device cameras
`
fun switchCameraTogglePressed() {
  // Get the current camera id
  val cameraId = cameraController.getCameraId()
  // Get the list of all cameras facing this direction
  val cameraIds = cameraController.getCameraIdsByFacing(camera.facing)
  if (cameraId == cameraIds[cameraIds.size-1]) {
    // This is the last camera this direction, switch to the other facing
    camera.facing = when (camera.facing) {
      FACING_BACK -> FACING_FRONT
      else -> FACING_BACK
    }
  } else {
    // Switch to the next camera
    camera.nextCamera()
  }
}
`
I can work up a PR including these items.

**Comment by pcm2a** [comment]
One other thing, not specific to this, when I updated this it started crashing because it couldn't find some coroutine classes. I added this to my build.gradle and the it worked. This was in my project that is using the camera library and not in the camera library.
`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1'`

**Comment by pcm2a** [comment]
@pvasa take a look at a few additions I made. Now you can know if there is more than one camera in the current facing direction. It also allows for switching between all the cameras, with a little extra logic in the client.

I tested this with the Camera2 api and also Camera1 by commenting out the api check. On a LG G6 I was able to swap between all cameras. It went in this order: 0 (back), 2 (back), 1 (front).

Code I used for swapping between all cameras.
```
    private fun cameraToggleClicked() {

        // Get the current camera id
        val cameraId = camera.getCameraId()
        // Get the list of all cameras facing this direction
        val cameraIds = camera.getCameraIdsByFacing()

        if (cameraId == cameraIds.elementAt(cameraIds.size-1)) {
            // This is the last camera this direction, switch to the other facing
            camera.facing = when (camera.facing) {
                FACING_BACK -> FACING_FRONT
                else -> FACING_BACK
            }
        } else {
            // Switch to the next camera
            camera.nextCamera()
        }
    }
```

**Comment by pvasa** [comment]
@pcm2a made some minor changes to make the api consistent also updated docs.

**Pull request merged**
