### PR TITLE
Provide video size to record in

### PR DESCRIPTION
**Pull request by pcm2a**
Currently the library will choose the highest video size in the current aspect ratio and based on the preview width/height. We should be able to specify exactly which size we want to record in. For example preview could be any size or shape but record in 1080p or 720p.

Added:
- Get the supported video sizes for the current camera
- Set the video size using VideoConfiguration

### CODE REVIEW

**Comment by pvasa** [comment]
Good idea. Although, a couple of things,
1. Relying on null value for anything is not really a good idea imo.
1. Freedom to choose any video size can lead to problems. Surface sizes are very restrictive in camera2 api. Some random weird media recorder surface size might end up showing blank screen.

To solve both these issues I would suggest defining a sealed class to restrict videoSize that can be passed in VideoConfiguration. Something like,
```
sealed class VideoSize {
    object Max : VideoSize()
    object P1080 : VideoSize()
    object P720 : VideoSize()
}
```

And then in `VideoConfiguration` have a property like `var videoSize: VideoSize = VideoSize.Max`. So based on this value, if it defaults to `Max` then `chooseOptimalSize(Template.Record)` shall be used otherwise different sizes accordingly.

**Comment by pcm2a** [comment]
I agree with everything except for not allowing the user to pick any supported size. The preview (surface view) has no relationship to what is supported for taking a picture or recording a video. For example you can have a 4:3 preview and record in 11:9 (176x144), assuming the camera supports that video size. Check out all the supported aspect ratios and sizes on a LG G6: https://pastebin.com/2f4Kfk4W

I like the idea of having some defaults and will refactor to a VideoSize class to support some preset values along with supporting any size.

**Comment by pcm2a** [comment]
I understand now why you wanted that limitation.
`setVideoSource(MediaRecorder.VideoSource.SURFACE)`

Using `VideoSource.SURFACE` instead of `VideoSource.CAMERA` limits us. I will go with your suggestion and not allow all sizes for now. I'm not sure what all would be involved with migrating away from SURFACE and using the CAMERA.

**Comment by pcm2a** [comment]
Update to allow 5 presets:
- SizeMax: The max for the previews aspect ratio, example 4:3 preview will get a 4:3 video)
- SizeMax16x9: The max for a 16:9 aspect, regardless of the preview aspect ratio
- SizeMax4:3: The max for a 4:3 aspect, regardless of the preview aspect ratio
- Size1080p: 1920x1080
- Size720p: 1280x720

Tested on LG G6 that with a 4:3 preview I could record using all 5 presets and the resulting video was the correct size.
Tested that emulator that supports a max of 720p, with a 4:3 preview, when choosing the Size1080p  the optimal size is chosen since 1080p is not supported.

**Comment by pvasa** [comment]
> Using `VideoSource.SURFACE` instead of `VideoSource.CAMERA` limits us. I will go with your suggestion and not allow all sizes for now. I'm not sure what all would be involved with migrating away from SURFACE and using the CAMERA.

If you see the [docs](https://developer.android.com/reference/android/media/MediaRecorder.VideoSource), they have clearly stated that `CAMERA` is for deprecated `camera1` api and for `camera2` `SURFACE` must be used.

**Comment by pvasa** [comment]
fixes #105

**Pull request merged**
